name: Update Top Contributors

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install requests

      - name: Run script
        env:
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN  }}
        run: python scripts/top_contributors.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/README.md
          git commit -m "feat: 🔄 Auto-update top contributors"
          git push