name: Update Top Contributors

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run contributor script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ORG: frontend-knowledge-hub
        run: node scripts/update-contributors.js

      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/README.md
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "feat: Auto-update top contributors"
            git push
          else
            echo "No changes to commit"
          fi